---
name: Haskell CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        ghc:
        - '8.6.5'
        - '8.8.3'
        # - '8.10.1' disabled until row-types gets bumped
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ls -l /opt/ghc/
        export PATH=/opt/ghc/bin:$PATH
        cabal --version
        ghc --version
        cabal update
        cabal v2-test -w ghc-${{ matrix.ghc }}
