---
name: Haskell CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        ghc:
        - '8.6.5'
        - '8.8.3'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ls -l /opt/ghc/
        export PATH=/opt/ghc/bin:$PATH
        cabal --version
        ghc --version
        cabal update
        # build first, so that the .ghc.environment file is written
        cabal build -w ghc-${{ matrix.ghc }}
        # then the doctest has a chance of succeeding
        cabal v2-test -w ghc-${{ matrix.ghc }}
